df <- read.csv("household_power_consumption.txt",sep=";", nrows=1)
colnames <- names(df)
df <- read.csv("household_power_consumption.txt",sep=";", skip=66636, nrows=2880)
names(df) <- colnames
df$datetime <- strptime(paste(df$Date,df$Time),"%d/%m/%Y %H:%M:%S")
png(filename="plot4.png", width=480, height=480)
par(mfrow = c(2,2))
with(df,plot(datetime, Global_active_power, type="l", xlab="", ylab="Global Active Power"))
with(df,plot(datetime, Voltage, type="l"))
plot(df$datetime, df$Sub_metering_1, type="n", xlab="", ylab="Energy sub metering")
points(df$datetime, df$Sub_metering_1, type="l")
points(df$datetime, df$Sub_metering_2, type="l", col="red")
points(df$datetime, df$Sub_metering_3, type="l", col="blue")
legend("topright", lty=1, bty="n", col=c("black","red","blue"), legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
with(df,plot(datetime, Global_reactive_power, type="l"))
dev.off()
