df <- read.csv("household_power_consumption.txt",sep=";", nrows=1)
colnames <- names(df)
df <- read.csv("household_power_consumption.txt",sep=";", skip=66636, nrows=2880)
names(df) <- colnames
df$Time <- strptime(paste(df$Date,df$Time),"%d/%m/%Y %H:%M:%S")
png(filename="plot3.png", width=480, height=480)
plot(df$Time, df$Sub_metering_1, type="n", xlab="", ylab="Energy sub metering")
points(df$Time, df$Sub_metering_1, type="l")
points(df$Time, df$Sub_metering_2, type="l", col="red")
points(df$Time, df$Sub_metering_3, type="l", col="blue")
legend("topright", lty=1, col=c("black","red","blue"), legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()